import Head from 'next/head';
import EventsSection from '../components/EventsSection';
import Header from '../components/Header';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ACM-W IITH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#B7D7E5]">
        <Navbar />
        <Header />
      </div>
      <EventsSection />
    </div>
  );
}
